# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: db_task
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080